### ISSUE TITLE
Lycanite's mobs compatibility issue

### ISSUE THREAD

**Issue by DLemberg** [ganymedes01/Headcrumbs#67]
Shadow mobs don't seem to be dropping heads.  For example, geists.  Looking into the LycanitesHelper.java I noticed that "shadowmobs" is missing from the prefix list.  I believe this might be causing the issue.

**Comment by buttilda** [comment]
I'm away from my laptop atm. If you could send a PR to fix that it would be greatly appreciated. Otherwise it will have to wait a bit.

Also, could you check the creative tab? If the heads aren't there then they definitely won't drop, but if they are then it could be something else causing the issue.
