### ISSUE TITLE
[Feature request] Friendly headcrumbs

### ISSUE THREAD

**Issue by ghost** [ganymedes01/Headcrumbs#74]
Instead of celebrity zombies, I'd like to have the heads on villagers. It could make the game more interesting in SSP.
(Bonus points for using the heads of the devs of the mods in the game. Double bonus for making mod's custom villagers have the dev's heads.)

**Comment by buttilda** [comment]
I actually started working on an add-on that did just that a while back haha

**Comment by helmutfork** [comment]
Possibly add a section in the configs for friendly and/or neutral mobs, so that certain names are always nice, while the rest are always hostile.

Also (and maybe this deserves it's own feature request entry), add compatibility with MineColonies mod so that headcrumbs mobs spawn as members of your colony.

**Comment by ghost** [comment]
@helmutfork You might want to ask the Minecolonies devs for that one. They already use custom models, so pulling up a skin might be something they'd agree to.
